Create a git repository in the test directory
The webpack configuration uses the hash of the commit to name files. So
some parent directory needs to be a git repository. This avoids the
error:

  > mypackagename@0.0.1 build /tmp/tmpEi8ahT/webpack
  > webpack -p

  fatal: not a git repository (or any of the parent directories): .git
  child_process.js:866
      throw err;
      ^

  Error: Command failed: git rev-list -1 HEAD -- `pwd`
  fatal: not a git repository (or any of the parent directories): .git